#!/bin/bash
#PBS -N CHAR_process_radtags_01
#PBS -l select=1:ncpus=16
#PBS -l walltime=48:00:00
#PBS -m e
#PBS -M 25405942@sun.ac.za

cd $PBS_O_WORKDIR

module load app/stacks/2.59

process_radtags -1 ~/msc/00_data/PLATE-1-AM_S231_L003_R1_001.fastq -2 ~/msc/00_data/PLATE-1-AM_S231_L003_R2_001.fastq \
                -o ~/msc/00_samples/ -b ~/msc/00_data/barcodes.txt -e sbfI -r -c -q -s 20 &> process_radtags.oe
