#!/bin/bash

#PBS -N 99_diyabc_neutral_investigation_bottleneck4
#PBS -l select=1:ncpus=16:mem=16GB
#PBS -l walltime=168:00:00
#PBS -m e
#PBS -M 25405942@sun.ac.za

cd ~/software/diyabcrf_neutral_investigation_bottleneck4

#Generate the seed for random data generation:
./diyabc-RF-linux-v1.1.54 -p ./ -n "t:32"

#Training set simulation:
./diyabc-RF-linux-v1.1.54 \
-p ./ -R "ALL" -r 16000 -g 50 -m -t 32

#Duplicate ref table
cp reftableRF.bin reftable.bin

 #Prior and scenario checking:
./diyabc-RF-linux-v1.1.54 -p ./ -d a:pl

# Model choice analysis on 15000 datasets
./abcranger-linux-v1.16.69 -n 16000 -t 1000 -j 32 -o modelchoice
./abcranger-linux-v1.16.69 -g "3,7,8;1,2,4,5,6" -n 16000 -t 1000 -j 32 -o modelchoice_grouped_SA_bottleneck
./abcranger-linux-v1.16.69 -g "2,3,6,7,8;1,4,5" -n 16000 -t 1000 -j 32 -o modelchoice_SA_change
./abcranger-linux-v1.16.69 -g "5,8;1,2,3,4,6,7" -n 16000 -t 1000 -j 32 -o modelchoice_AUS_bottleneck
./abcranger-linux-v1.16.69 -g "4,5,6,7,8;1,2,3" -n 16000 -t 1000 -j 32 -o modelchoice_AUS_change
./abcranger-linux-v1.16.69 -g "3,5,7,8;1,2,4,6" -n 16000 -t 1000 -j 32 -o modelchoice_bottleneck
./abcranger-linux-v1.16.69 -g "2,3,4,5,6,7,8;1" -n 16000 -t 1000 -j 32 -o modelchoice_change
