#!/bin/bash

#PBS -N 99_diyabc_neutral_investigation_bottleneck_parameter3b
#PBS -l select=1:ncpus=36:mem=8GB
#PBS -l walltime=168:00:00
#PBS -m e
#PBS -M 25405942@sun.ac.za

cd ~/software/diyabcrf_neutral_investigation_bottleneck_parameter3

#Simulation of a training set with 10000 particles for only 

for param in \
N1 N2 r1 N2a N1a NAa NAb NAc NAd Tad1 T2a T1a Td TAa TAb TAc \
; do
./abcranger-linux-v1.16.69 -n 10000 -t 1000 -j 32 --parameter $param --chosenscen 1 \
--plsmaxvar 0.95 --noob 10000 -o estim_param_ra_with_PLS_$param
done
