#!/bin/bash
#PBS -N 99_stairway_SA_31
#PBS -l select=1:ncpus=16:mem=10GB
#PBS -l walltime=168:00:00
#PBS -o logs_SA/
#PBS -e logs_SA/
#PBS -m e
#PBS -M 25405942@sun.ac.za

cd $PBS_O_WORKDIR

cd ~/software/stairway_plot_v2.1/stairway_plot_v2.1.1/

bash SA_fold.blueprint_31.sh
